---
security:
  basic:
    enabled: false

management:
  security:
    enabled: false

spring:
  application:
    name: probate-persistence-service
  jpa:
    database: POSTGRESQL
    show-sql: ${probate.persistence.show_sql}
    hibernate.ddl-auto: none
    database-platform:  uk.gov.hmcts.probate.services.persistence.hibernate.JsonPostgresSQL94Dialect

  datasource:
    url: jdbc:postgresql://${probate.postgresql.hostname}:${probate.postgresql.port}/${probate.postgresql.database}
    username:  ${probate.postgresql.user}
    password:  ${probate.postgresql.password}

  database.driverClassName: org.postgresql.Driver


server:
  port: ${probate.persistence.port}


registries:
    - id: oxford
      email: oxford@email.com
      address: |
        Line 1 Ox
        Line 2 Ox
        Line 3 Ox
        PostCode Ox
      ratio: 4
    - id: birmingham
      email: birmingham@email.com
      address: |
        Line 1 Bham
        Line 2 Bham
        Line 3 Bham
        PostCode Bham
      ratio: 1
    - id: manchester
      email: manchester@email.com
      address: |
        Line 1 man
        Line 2 man
        Line 3 man
        PostCode Manchester
      ratio: 2


logging:
  level:
    org.springframework.web: ERROR
    uk.gov.hmcts.probate: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:false}

spring.liquibase:
  enabled: ${LIQUIBASE_AT_STARTUP:false}

