---
spring:
  application:
    name: probate-persistence-service

  jpa:
    database: POSTGRESQL
    show-sql: ${probate.persistence.show_sql}
    hibernate.ddl-auto: none
    database-platform:  uk.gov.hmcts.probate.services.persistence.hibernate.JsonPostgresSQL94Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    url: jdbc:postgresql://${probate.postgresql.hostname}:${probate.postgresql.port}/${probate.postgresql.database}
    username:  ${probate.postgresql.user}
    password:  ${probate.postgresql.password}
    driverClassName: org.postgresql.Driver

  liquibase:
    enabled: ${LIQUIBASE_AT_STARTUP:false}

management:
  endpoints:
    web:
      base-path: '/'
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server:
  port: ${probate.persistence.port}

registries:
  - oxford
  - birmingham
  - manchester

logging:
  level:
    org.springframework.web: ERROR
    uk.gov.hmcts.probate: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:false}