---


spring:
  application:
    name: probate-persistence-service
  jpa:
    database: POSTGRESQL
    show-sql: ${probate.persistence.show_sql}
    hibernate.ddl-auto: none
    database-platform:  uk.gov.hmcts.probate.services.persistence.hibernate.JsonPostgresSQL94Dialect

  datasource:
    url: jdbc:postgresql://${probate.postgresql.hostname}:${probate.postgresql.port}/${probate.postgresql.database}
    username:  ${probate.postgresql.user}
    password:  ${probate.postgresql.password}

  database.driverClassName: org.postgresql.Driver

server:
  port: ${probate.persistence.port}
