postgresql:
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  postgresqlDatabase: user-profile
  nameOverride: ccd-postgres
  initdbScripts:
    init.sql: |-
      CREATE DATABASE "data-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  persistence:
    enabled: false
java:
  configmap:
  SPRING_APPLICATION_JSON : '{"registries":["oxford","birmingham","manchester"]}'