java:
  applicationPort: 8282
  environment:
    REFORM_TEAM: probate
    REFORM_SERVICE_NAME: persistence-service
    MAIL_JAVAMAILPROPERTIES_MAIL_SMTP_SSL_ENABLE: false
    MAIL_JAVAMAILPROPERTIES_MAIL_SMTP_AUTH: false
    SERVICES_CORECASEDATA_ENABLED: true
    MAIL_JAVAMAILPROPERTIES_SUBJECT: "Probate Application"
    AUTH_PROVIDER_SERVICE_CLIENT_KEY: ${S2S_AUTH_TOTP_SECRET}
    MAIL_USERNAME: ${PROBATE_SUB_MAIL_USERNAME}
    MAIL_PASSWORD: ${PROBATE_SUB_MAIL_PASSWORD}
    MAIL_HOST: ${PROBATE_SUB_MAIL_HOST}
    MAIL_PORT: ${PROBATE_SUB_MAIL_PORT}
    MAIL_JAVAMAILPROPERTIES_SENDER: ${PROBATE_SUB_MAIL_SENDER}
    MAIL_JAVAMAILPROPERTIES_RECIPIENT: ${PROBATE_SUB_MAIL_REC}
    SERVICES_CORECASEDATA_BASEURL : ${SERVICE_NAME}-data-store-api
    # SERVICES_CORECASEDATA_BASEURL : ${SERVICE_NAME}-ccd-data-store-api

postgresql:
  postgresqlUsername: probate
  postgresqlPassword: probate
  postgresqlDatabase: shared-profile
  nameOverride: shared-database
  initdbScripts:
    init.sql: |-
      CREATE DATABASE "probate" WITH OWNER = probate ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  persistence:
    enabled: false


  # Don't modify below here.
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
